version: '3.8'

services:
  db:
    image: postgres:15-alpine # Alpine is very small and efficient
    container_name: inventory_db
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-password}
      POSTGRES_DB: ${POSTGRES_DB:-inventory_db}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - inventory_network

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: inventory_backend
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      # Connect using the service name 'db'
      - DATABASE_URL=postgresql://${POSTGRES_USER:-postgres}:${POSTGRES_PASSWORD:-password}@db:5432/${POSTGRES_DB:-inventory_db}
    depends_on:
      - db
    networks:
      - inventory_network

  frontend:
    build: ./frontend
    container_name: inventory_frontend
    environment:
      - VITE_API_URL=http://backend:8000/api/v1 # Internal Docker network URL
    ports:
      - "5173:80"
    networks:
      - inventory_network

networks:
  inventory_network:
    driver: bridge

volumes:
  postgres_data: